version: "3.3"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.2-community
    depends_on:
      - db
    ports:
      - "${EXPOSED_PORT}:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: ${SQ_JDBC_USER}
      SONAR_JDBC_PASSWORD: ${SQ_JDBC_PASSWORD}
    volumes:
      - data:/opt/sonarqube/data
      - extensions:/opt/sonarqube/extensions
      - logs:/opt/sonarqube/logs
      - temp:/opt/sonarqube/temp
    deploy:
      resources:
        limits:
          memory: ${SQ_MEMORY}
  db:
    container_name: postgres
    image: postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: ${SQ_JPOSTGRES_USER}
      POSTGRES_PASSWORD: ${SQ_POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEMORY}
networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  extensions:
  logs:
  temp:
  postgresql:
  postgresql_data:
